Feature: Added  `source_dynamic`, replacing `source_generated`
Changes:
 - renamed `source_generated` to `source_dynamic`
 - added `source_dynamic-mktemp` and `source_dynamic-source` for use without process substitution

diff --git a/bin/activate b/bin/activate
--- a/bin/activate
+++ b/bin/activate
@@ -43,10 +43,34 @@ fi
 
 ## Declare public functions
 
+# A pair of helper functions to simplify sourcing dynamically-generated shell code without process substitution `<(...)`
+
+# Creates a temporary file to store the dynamic output
+source_dynamic-mktemp() {
+    # Create a private temporary file
+    mktemp "${XDG_RUNTIME_DIR-"${TMPDIR-"/tmp"}"}"/ansiblesite-source_dynamic.XXXXXX
+}
+
+# Sources a temporary file and removes it
+source_dynamic-source() {
+    # Declare variables
+    local RC
+
+    # Source the temporary file with its arguments and save exit status
+    RC=0
+    # shellcheck disable=SC1090
+    source "$@" || RC=$?
+
+    # Remove the temporary file
+    rm "$1"
+
+    return $RC
+}
+
 # Helper function to add compatibility of sourcing dynamically-generated shell code
-# in older bash version
+# in older bash version, uses the `source_dynamic-mktemp` and `source_dynamic-process` helper functions
 if [[ "$_ANSIBLESITE_SHELL" = 'bash' && "$BASH_VERSINFO" -le 3 ]]; then
-    source_generated() {
+    source_dynamic() {
 
         # Declare variables
         local SCRIPT_FD SCRIPT_TEMP RC
@@ -55,26 +79,18 @@ if [[ "$_ANSIBLESITE_SHELL" = 'bash' && "$BASH_VERSINFO" -le 3 ]]; then
         SCRIPT_FD="$1"
         shift
 
-        # Create a private temporary file
-        SCRIPT_TEMP="$(mktemp "${XDG_RUNTIME_DIR-"${TMPDIR-"/tmp"}"}"/bash-source-generated.XXXXXX)"
+        # Get a private temporary file
+        SCRIPT_TEMP="$(source_dynamic-mktemp)"
 
         # Put the contents of the dynamically-generated file to the temporary file
         cat "$SCRIPT_FD" > "$SCRIPT_TEMP"
 
-        # Source the temporary file and save exit status
-        RC=0
-        # shellcheck disable=SC1090
-        source "$SCRIPT_TEMP" "$@" || RC=$?
-
-        # Remove the temporary file
-        rm "$SCRIPT_TEMP"
-
-        # Return with the exit code of the sourced script
-        return $RC
+        # Source the shell code
+        source_dynamic-source "$SCRIPT_TEMP" "$@"
 
     }
 else
-    source_generated() {
+    source_dynamic() {
         # shellcheck disable=SC1090
         source "$@"
     }
@@ -239,7 +255,7 @@ if [[ "$ANSIBLESITE_USE_VENV" -eq 1 ]]; then
 
         # rename the deactivation function to '_venv_deactivate'
         # to avoid conflict with the deactivation function of this script
-        source_generated <(declare -f deactivate | sed 's/deactivate/_venv_deactivate/')
+        source_dynamic <(declare -f deactivate | sed 's/deactivate/_venv_deactivate/')
         unset -f deactivate
 
     # ... or handle the situation when venv is required but missing
@@ -313,7 +329,7 @@ deactivate() {
     unset ANSIBLESITE_PROFILE
 
     # unset public functions
-    unset -f source_generated
+    unset -f source_dynamic
 
     # unset internal functions
     unset -f _get_indirect
